<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="stripes"	uri="http://stripes.sourceforge.net/stripes.tld"%>
<stripes:layout-render name="/Layouts/eve.jsp">
	<stripes:layout-component name="PageContent">
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed dolor nec quam lacinia sagittis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque luctus mauris vel metus tincidunt ullamcorper. Sed congue turpis libero. Fusce pharetra sapien nec nisl venenatis auctor. Aenean a varius nulla. In ornare risus et est adipiscing cursus nec eu erat. Morbi et sem id risus fermentum gravida. Donec lobortis ipsum ut orci tincidunt mollis. Etiam semper purus quis ipsum viverra feugiat. Quisque ullamcorper arcu vel mauris volutpat posuere. Duis tempor varius arcu sit amet faucibus. Aenean vitae dolor ac justo vestibulum convallis.

Ut metus dui, accumsan eget viverra at, mollis commodo ipsum. Nulla hendrerit justo ut lectus dapibus vulputate placerat nisi ullamcorper. Integer et nulla sit amet arcu feugiat egestas. Nulla rutrum blandit quam vitae auctor. Maecenas commodo est a nunc rhoncus sit amet vulputate ante pellentesque. Vestibulum sit amet eros nulla. Pellentesque consequat placerat nibh, non sodales metus mollis sed. Duis tristique malesuada elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus quis vestibulum nunc. Aenean ante est, vestibulum et pulvinar quis, malesuada non leo. Praesent id nisl purus. Curabitur ultricies neque a nibh malesuada ac porta justo malesuada. Quisque eget eros id turpis lobortis commodo. Donec venenatis dapibus feugiat. Nunc ligula magna, dictum non pellentesque ac, consequat nec erat. In tincidunt ipsum sed orci tincidunt ultricies. Donec non neque eros, eleifend scelerisque lorem. Nunc semper facilisis nisl, vitae ornare lectus dignissim cursus.

Aliquam in urna dui, eu cursus tellus. Praesent eu consequat metus. Nam diam quam, ullamcorper sit amet dapibus in, ornare a lectus. Donec cursus nisi quis orci interdum laoreet. Nunc mattis pretium scelerisque. Morbi vestibulum volutpat enim vitae blandit. Maecenas sed odio id enim rutrum sollicitudin nec eget dui. Sed nunc neque, dapibus pellentesque accumsan sollicitudin, faucibus sed justo. Aenean mattis facilisis lorem at dapibus. Nulla sit amet laoreet dui. Phasellus iaculis rhoncus nisl, non sollicitudin lacus dignissim ac. Nunc rutrum, nisi in hendrerit sagittis, turpis turpis scelerisque eros, quis hendrerit nisl erat sit amet mi. Sed convallis elementum enim id aliquet. Sed mollis ipsum quam. Aliquam tincidunt magna a tortor aliquet venenatis. Donec vulputate luctus enim, ut aliquam orci egestas vehicula. Donec sed est urna, varius molestie neque. Aenean imperdiet, erat vestibulum mollis gravida, augue lacus faucibus ante, eu ultrices quam erat molestie eros.

Aenean ullamcorper, dolor ac porttitor adipiscing, nisi mi molestie nisl, sed adipiscing mauris enim eget quam. Fusce interdum pharetra sem, eu viverra ligula vehicula at. Nullam eu rutrum enim. Pellentesque pellentesque lobortis felis, at tincidunt purus egestas eget. Ut eu augue sed purus tempus varius id a elit. Vivamus nunc tortor, imperdiet sed dictum ac, porttitor ut lectus. Nulla iaculis dapibus leo et varius. Integer sem purus, sodales et pretium vel, posuere sed lectus. Cras egestas, nunc eget sollicitudin hendrerit, quam purus pretium tellus, et mollis dolor augue quis nulla. Proin dictum, libero id sagittis interdum, diam nisi eleifend leo, nec ultricies nunc nunc id elit. Suspendisse lobortis sem id nibh dapibus ac mattis quam tempus. Donec fringilla neque in tellus pharetra hendrerit. Nulla non mi nec ligula gravida scelerisque nec quis lacus. Suspendisse molestie porttitor nisl, vel sodales diam faucibus id. Morbi et neque faucibus libero congue mattis. Phasellus ullamcorper ligula ac orci dignissim dapibus. Donec sodales lacus mollis massa viverra pellentesque. Morbi arcu urna, eleifend a accumsan id, euismod a urna. Integer volutpat tortor nec ipsum iaculis accumsan. Phasellus aliquam, enim a sodales scelerisque, nunc ante laoreet diam, sed ullamcorper ante sapien eu nisi.

Donec ut tortor leo. Nam viverra rutrum tortor, vel adipiscing nibh blandit eu. In luctus fringilla nulla ut faucibus. Aenean eget magna ligula, sed aliquet risus. Proin id lorem ut felis ultrices adipiscing. In dignissim tortor non velit eleifend gravida. Vivamus nec nunc metus, id hendrerit sapien. Mauris varius, lectus lacinia posuere convallis, dolor nulla sollicitudin sem, at tristique nibh augue a lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed suscipit viverra sem adipiscing rhoncus. Phasellus aliquet mi vel tortor euismod auctor.
		
	</stripes:layout-component>
</stripes:layout-render>