package nz.net.dnh.evetool.hibernate.evetool;

// Generated 10/08/2011 3:49:46 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AuthorisedCorporations generated by hbm2java
 */
@Entity
@Table(name = "AuthorisedCorporations", catalog = "EVETool")
public class AuthorisedCorporations implements java.io.Serializable {

	private AuthorisedCorporationsId id;

	public AuthorisedCorporations() {
	}

	public AuthorisedCorporations(AuthorisedCorporationsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "corpId", column = @Column(name = "CorpID", nullable = false)),
			@AttributeOverride(name = "corpName", column = @Column(name = "CorpName", nullable = false, length = 65535)),
			@AttributeOverride(name = "findable", column = @Column(name = "Findable", nullable = false)) })
	public AuthorisedCorporationsId getId() {
		return this.id;
	}

	public void setId(AuthorisedCorporationsId id) {
		this.id = id;
	}

}
