package nz.net.dnh.evetool.hibernate.evetool;

// Generated 10/08/2011 3:49:46 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuthorisedCorporationsId generated by hbm2java
 */
@Embeddable
public class AuthorisedCorporationsId implements java.io.Serializable {

	private int corpId;
	private String corpName;
	private boolean findable;

	public AuthorisedCorporationsId() {
	}

	public AuthorisedCorporationsId(int corpId, String corpName,
			boolean findable) {
		this.corpId = corpId;
		this.corpName = corpName;
		this.findable = findable;
	}

	@Column(name = "CorpID", nullable = false)
	public int getCorpId() {
		return this.corpId;
	}

	public void setCorpId(int corpId) {
		this.corpId = corpId;
	}

	@Column(name = "CorpName", nullable = false, length = 65535)
	public String getCorpName() {
		return this.corpName;
	}

	public void setCorpName(String corpName) {
		this.corpName = corpName;
	}

	@Column(name = "Findable", nullable = false)
	public boolean isFindable() {
		return this.findable;
	}

	public void setFindable(boolean findable) {
		this.findable = findable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthorisedCorporationsId))
			return false;
		AuthorisedCorporationsId castOther = (AuthorisedCorporationsId) other;

		return (this.getCorpId() == castOther.getCorpId())
				&& ((this.getCorpName() == castOther.getCorpName()) || (this
						.getCorpName() != null
						&& castOther.getCorpName() != null && this
						.getCorpName().equals(castOther.getCorpName())))
				&& (this.isFindable() == castOther.isFindable());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCorpId();
		result = 37 * result
				+ (getCorpName() == null ? 0 : this.getCorpName().hashCode());
		result = 37 * result + (this.isFindable() ? 1 : 0);
		return result;
	}

}
