package nz.net.dnh.evetool.hibernate.evetool;

// Generated 10/08/2011 3:49:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Corporation generated by hbm2java
 */
@Entity
@Table(name = "Corporation", catalog = "EVETool")
public class Corporation implements java.io.Serializable, nz.net.dnh.evetool.entities.evetool.Corporation {

	private int corpId;
	private String corpName;
	private boolean findable;
	private Set<User> users = new HashSet<User>(0);

	public Corporation() {
	}

	public Corporation(int corpId, String corpName, boolean findable) {
		this.corpId = corpId;
		this.corpName = corpName;
		this.findable = findable;
	}

	public Corporation(int corpId, String corpName, boolean findable,
			Set<User> users) {
		this.corpId = corpId;
		this.corpName = corpName;
		this.findable = findable;
		this.users = users;
	}

	@Id
	@Column(name = "CorpID", unique = true, nullable = false)
	public int getCorpId() {
		return this.corpId;
	}

	public void setCorpId(int corpId) {
		this.corpId = corpId;
	}

	@Column(name = "CorpName", nullable = false, length = 65535)
	public String getCorpName() {
		return this.corpName;
	}

	public void setCorpName(String corpName) {
		this.corpName = corpName;
	}

	@Column(name = "Findable", nullable = false)
	public boolean isFindable() {
		return this.findable;
	}

	public void setFindable(boolean findable) {
		this.findable = findable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "corporation")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
