package nz.net.dnh.evetool.hibernate.evetool;

// Generated 10/08/2011 3:49:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "Module", catalog = "EVETool", uniqueConstraints = @UniqueConstraint(columnNames = "ModuleName"))
public class Module implements java.io.Serializable {

	private int moduleId;
	private String moduleName;
	private Set<Rule> rules = new HashSet<Rule>(0);
	private Module parent;

	public Module() {
	}

	public Module(String moduleName) {
		this.moduleName = moduleName;
	}

	public Module(String moduleName, Set<Rule> rules,
			Module parent) {
		this.moduleName = moduleName;
		this.rules = rules;
		this.parent = parent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ModuleID", unique = true, nullable = false)
	public int getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "ModuleName", unique = true, nullable = false, length = 64)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Rule> getRules() {
		return this.rules;
	}

	public void setRules(Set<Rule> rules) {
		this.rules = rules;
	}

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinTable(name="ModuleParent", joinColumns={@JoinColumn(name="ModuleID")}, inverseJoinColumns={@JoinColumn(name="ParentID")})
	public Module getParent() {
		return this.parent;
	}
	
	public void setParent(Module parent) {
		this.parent = parent;
	}
}
